name: Warp
version: 1.0.4
api-version: 1.17
main: kr.skymin.warp.Loader
author: skymin

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.21
  - org.jetbrains.kotlin:kotlin-reflect:1.8.21
  - io.github.monun:kommand-core:3.1.3
